### ISSUE TITLE
Not working when adding to or removing from favorites

### ISSUE THREAD

**Issue by vancez** [stuarthayhurst/alphabetical-grid-extension#6] opened 2021-05-30 07:15 UTC

**Comment by stuarthayhurst** [comment] 2021-05-30 08:37
Can you provide any more information? A description, a log, a screenshot or video? I don't really know what's wrong here.

**Comment by vancez** [comment] 2021-05-30 08:46
> Can you provide any more information? A description, a log, a screenshot or video? I don't really know what's wrong here.

When added to favorites, the app will be removed from the app grid, leaving an empty place, and will not be reordered.
When deleted from favorites, the app are simply appended to the end of the grid out of order.

**Comment by vancez** [comment] 2021-05-30 08:48
> > Can you provide any more information? A description, a log, a screenshot or video? I don't really know what's wrong here.
> 
> When added to favorites, the app will be removed from the app grid, leaving an empty place, and will not be reordered.
> When deleted from favorites, the app are simply appended to the end of the grid out of order.

![image](https://user-images.githubusercontent.com/40771709/120098127-b86e6680-c166-11eb-97bf-3f85f3584a91.png)
After adding to favorites.

**Comment by stuarthayhurst** [comment] 2021-05-30 08:48
Thanks for more info, I should be able to fix this quite easily

**Comment by daPhipz** [comment] 2021-05-30 09:03
@vancez Are you using GNOME 40?
AFAIK 3.38 doesn't remove favourites from the app grid.

**Comment by stuarthayhurst** [comment] 2021-05-30 09:11
I've tested on GNOME 40 in a VM and I can't reproduce what they're describing, but it is still a little buggy. I can fix it by triggering a reorder of the grid when 'favourite-apps' changes, but I can't fix much on GNOME 3.38 as it's not really possible to refresh the order without restarting the shell.

**Comment by vancez** [comment] 2021-05-30 09:14
Yes, I use GNOME 40 on archlinux.

> @vancez Are you using GNOME 40?
> AFAIK 3.38 doesn't remove favourites from the app grid.

**Comment by stuarthayhurst** [comment] 2021-05-30 10:18
@vancez  This should be fixed on master, if you could test, that'd be great :)

**Comment by vancez** [comment] 2021-05-30 10:29
> @vancez This should be fixed on master, if you could test, that'd be great :)

It works, thanks for the fixes.

**Closed** 2021-05-30 10:29 UTC
