### ISSUE TITLE
[Bug] Systems with many apps have missing entries after reboot

### ISSUE THREAD

**Issue by LuNeder** [stuarthayhurst/alphabetical-grid-extension#67] opened 2022-05-14 15:31 UTC
**Describe the issue**
After a reboot, the app grid is basically empty. Very few apps show. This is only fixed by disabling and then reenabling the extension.

**To Reproduce**
1. Enable extension, works fine
2. Reboot
3. Only a few apps in there, most apps are vanished (searching works fine tho)
4. Disable extension
5. Apps still missing
6. Enable extension again
7. Apps are back

**Expected behavior**
I expect my apps not to disappear from app grid after a reboot

**Screenshots and logs**
When working fine:
![image](https://user-images.githubusercontent.com/19750714/168436817-6f436f60-9084-4479-ad60-5f48572c5646.png)

After a reboot:
![image](https://user-images.githubusercontent.com/19750714/168437610-89b19813-a3b1-4c74-8072-acb7cbf06c16.png)

I'll add the logs once I get back home

**System information (please complete the following information):**
 - Distro: OpenSUSE Tumbleweed
 - GNOME version: 42.1
 - Extension version: 23

**Comment by LuNeder** [comment] 2022-05-14 18:23
Here are the logs:

[appgridmissing.txt](https://github.com/stuarthayhurst/alphabetical-grid-extension/files/8693665/appgridmissing.txt)

**Comment by stuarthayhurst** [comment] 2022-05-14 18:26
This seems similar to a previous bug I thought I fixed, thanks for the report, I'll take a closer look when I get time

**Comment by Aurnytoraink** [comment] 2022-05-21 15:18
I do have the same problem on Fedora Silverblue. Here are my logs : [log.txt](https://github.com/stuarthayhurst/alphabetical-grid-extension/files/8747857/log.txt)

**Comment by didierga** [comment] 2022-06-18 09:49
Since few days I have the same bug using Fedora 36 with gnome-shell 42 and xorg.

I have to disable/enable extension to see all applications.

**Comment by Anifyuli** [comment] 2022-07-31 08:50
Sorry, My brother. In my system, that bug feel worse than it. After disable and enable extension again, it not showing properly. This screenshot will help to explain this bug
![Screenshot from 2022-07-31 09-55-06](https://user-images.githubusercontent.com/73734843/182008929-aeb211aa-14a0-49e4-9c4f-d04c9bc20a75.png)

Thanks for solve this problem

**Comment by stuarthayhurst** [comment] 2022-07-31 10:07
This is still similar to a previous issue, where when a user had many apps installed, they're begin disappearing. The fix at the time for that was mostly by chance and sort of hacky, I'm not really sure what causes this. It's also very difficult to reproduce in virtual machines, and randomly fixed itself from my testing. If I can think of a fix I'll apply it, but right now I'm sort of stumped.

**Comment by Anifyuli** [comment] 2022-07-31 12:15
> This is still similar to a previous issue, where when a user had many apps installed, they're begin disappearing. The fix at the time for that was mostly by chance and sort of hacky, I'm not really sure what causes this. It's also very difficult to reproduce in virtual machines, and randomly fixed itself from my testing. If I can think of a fix I'll apply it, but right now I'm sort of stumped.

Ok, Brother. Thanks for your explanation. I hope you can always maintain this project

**Comment by cowboysmall** [comment] 2022-09-04 09:23
I'm seeing the same issue - Fedora 36, Gnome 42.4, Wayland, Alphabetical App Grid 25. 

Restarting the plugin will restore the missing apps.

One thing I have noticed though is that of the three laptops I have running F36, only one was upgraded from F35, and that is the one that has the problem - the other two do not have this issue. So this issue not apparent on two laptops with a fresh install of F36, but issue apparent on laptop upgraded from F35 to F36.

**Comment by stuarthayhurst** [comment] 2022-09-22 22:43
Another affected user [here](https://www.reddit.com/r/gnome/comments/xiiwds/um_where_are_all_my_apps_in_the_app_drawer/), added for info.
Hopefully next time I update this, it'll be with a fix.

**Comment by haluzpav** [comment] 2022-09-26 18:13
I report the same problem - no apps visible with the extensions enabled.

**Comment by Scotty-Trees** [comment] 2022-11-18 04:32
Just noticed this started happening randomly on Ubuntu 22.04.1 LTS. Had been working fine for the past 3 months otherwise. I have to disable the extension and reboot if I want all my apps to show up properly and completely in the apps grid. With it turned on, 90% of the apps in my app grid are "missing" on a reboot. For now I've turned off the extension, but since this is an old bug I hope it can be fixed still. 

Please let me know if I can provide any additional logs or information to help, thank you.

**Comment by stuarthayhurst** [comment] 2023-01-15 20:18
This might be fixed on `master`

If you clone master can you do the following please: (you might need `gettext` installed)
```
make build
make install
```
Then reboot to make sure it took effect

**Comment by stuarthayhurst** [comment] 2023-01-20 18:35
Pushed a new release, if this fixes it for anyone. Let me know whether this issue is still present in the latest version :)

Thanks!

**Comment by stuarthayhurst** [comment] 2023-02-21 00:58
Closing, feel free to re-open if this still affects anyone with the latest version (v27)

**Closed** 2023-02-21 00:58 UTC
Labels: bug
