### ISSUE TITLE
UI strings may not get updated with "make translations"

### ISSUE THREAD

**Issue by daPhipz** [stuarthayhurst/alphabetical-grid-extension#38] opened 2021-08-31 11:07 UTC
**Describe the issue**
When running `make translations`, some changes to strings in the UI don't get picked up.

**To Reproduce**
1. Edit a string in the UI via Glade (I changed the context of the folder position strings `"Alphabetical"`, `"Start"` and `"End"`)
2. Run `make translations`
3. The string is now present twice in the `po` files (one time with the old context, one time with the new context).

**Expected behavior**
The old string should have disappeared.

**Possible solution**
Run `make gtk4` before `make translations`.

Since I don't really know what `make gtk4` does, I am opening this issue. I assume it parses the `/ui/prefs.ui` file in some way to be compatible with GTK4. Is this correct?
It could be that (when `make gtk4` has not been run) the old version of the strings is still in `/ui/prefs-gtk4.ui` - and therefore not removed from the `po` files.

**Comment by stuarthayhurst** [comment] 2021-08-31 11:26
`make gtk4` converts the .ui file that glade creates for GTK+ 3 into a version for GTK+ 4, using binaries provided by `libgtk4-bin`. This is more or less expected behaviour I guess, as `make gtk4` should be run after every UI modification.
If it's not run, and then `make translations` is run, both strings appear as I guess it picks them up as different due to the context, so it keeps both strings so it can translate either.
This is also why `make gtk4` comes before `make translations` in `make release`

**Comment by stuarthayhurst** [comment] 2021-08-31 11:30
We could set the `gtk4` target as a dependency of `translations`, but this would mean to run `make translations`, you would need `libgtk4-bin`, even if no changes had been made to the UI.

**Comment by stuarthayhurst** [comment] 2021-08-31 11:35
I wouldn't normally have a problem with just running `gtk4` before `translations` automatically, but `libgtk4-bin` isn't in every distro, which might make the translations a little less accessible. The other side effect is that you may not want to generate the GTK+ 4 .ui file if you were testing something, but that's only a minor side effect.

Alternatively, I could reorganise the documentation on the build system to mention this quirk, as well as mentioning it on the "Want to help?" section. As the repository has been getting some attention, I'm also planning to write some contribution guidelines, based off of what I've already written for my other projects, and I could mention running `make gtk4` before `make translations` there too.

Let me know what you think :)

**Comment by daPhipz** [comment] 2021-08-31 11:43
> `libgtk4-bin` isn't in every distro

I'm fine with running `make gtk4` before `make translations`, but I think mentioning it in the docs is a very good idea!

**Comment by stuarthayhurst** [comment] 2021-08-31 11:48
Cool, I'll work on adding this with the rest of the documentation improvements. Thanks for catching this!

**Comment by stuarthayhurst** [comment] 2021-09-01 11:59
Fixed on master

**Closed by stuarthayhurst** 2021-09-01 11:59 UTC
Labels: bug
